"""Public import surface for the GLPI Python client package.

The package re-exports two client classes:

* :class:`GlpiClient` — synchronous, blocking client.
* :class:`AsyncGlpiClient` — asynchronous client doing real
  non-blocking I/O on the event loop.

They expose identical endpoint surfaces because they are the same
code: the async tree is hand-written and the sync one is generated
from it. Neither is a wrapper around the other.

The ``api_schema`` and ``custom_schema`` Pydantic models are also
re-exported so downstream users can import them from a single stable
package root.
"""

from __future__ import annotations

from glpi_python_client._async.clients import AsyncGlpiClient
from glpi_python_client._errors import (
    GlpiAuthError,
    GlpiError,
    GlpiNotFoundError,
    GlpiProtocolError,
    GlpiServerError,
    GlpiStatusError,
    GlpiTimeoutError,
    GlpiTransportError,
    GlpiValidationError,
)
from glpi_python_client._sync.clients import GlpiClient
from glpi_python_client.models import (
    DeleteDocument,
    DeleteEntity,
    DeleteFollowup,
    DeleteKBArticle,
    DeleteKBArticleComment,
    DeleteKBCategory,
    DeleteLocation,
    DeleteSolution,
    DeleteTeamMember,
    DeleteTicket,
    DeleteTicketTask,
    DeleteTimelineDocument,
    DeleteUser,
    GetDocument,
    GetEntity,
    GetFollowup,
    GetKBArticle,
    GetKBArticleComment,
    GetKBArticleRevision,
    GetKBCategory,
    GetLocation,
    GetPluginFieldsContainer,
    GetPluginFieldsField,
    GetPluginFieldsValueRow,
    GetSolution,
    GetTeamMember,
    GetTicket,
    GetTicketTask,
    GetTimelineDocument,
    GetUser,
    GlpiEnum,
    GlpiGlobalValidation,
    GlpiPriority,
    GlpiSolutionStatus,
    GlpiTaskState,
    GlpiTicketContext,
    GlpiTicketStatus,
    GlpiTicketType,
    GlpiTimelinePosition,
    GlpiUserAuthType,
    IdNameCompletenameRef,
    IdNameRef,
    IdRef,
    PatchDocument,
    PatchEntity,
    PatchFollowup,
    PatchKBArticle,
    PatchKBArticleComment,
    PatchKBCategory,
    PatchLocation,
    PatchSolution,
    PatchTeamMember,
    PatchTicket,
    PatchTicketTask,
    PatchTimelineDocument,
    PatchUser,
    PostDocument,
    PostEntity,
    PostFollowup,
    PostKBArticle,
    PostKBArticleComment,
    PostKBCategory,
    PostLocation,
    PostPluginFieldsValueRow,
    PostSolution,
    PostTeamMember,
    PostTicket,
    PostTicketTask,
    PostTimelineDocument,
    PostUser,
    TicketMarkdownOptions,
)
from glpi_python_client.rsql import (
    changed_since,
    created_between,
    date_window,
)

__version__ = "0.4.2"

__all__ = [
    "AsyncGlpiClient",
    "DeleteDocument",
    "DeleteEntity",
    "DeleteFollowup",
    "DeleteKBArticle",
    "DeleteKBArticleComment",
    "DeleteKBCategory",
    "DeleteLocation",
    "DeleteSolution",
    "DeleteTeamMember",
    "DeleteTicket",
    "DeleteTicketTask",
    "DeleteTimelineDocument",
    "DeleteUser",
    "GetDocument",
    "GetEntity",
    "GetFollowup",
    "GetKBArticle",
    "GetKBArticleComment",
    "GetKBArticleRevision",
    "GetKBCategory",
    "GetLocation",
    "GetPluginFieldsContainer",
    "GetPluginFieldsField",
    "GetPluginFieldsValueRow",
    "GetSolution",
    "GetTeamMember",
    "GetTicket",
    "GetTicketTask",
    "GetTimelineDocument",
    "GetUser",
    "GlpiAuthError",
    "GlpiClient",
    "GlpiEnum",
    "GlpiError",
    "GlpiGlobalValidation",
    "GlpiNotFoundError",
    "GlpiPriority",
    "GlpiProtocolError",
    "GlpiServerError",
    "GlpiSolutionStatus",
    "GlpiStatusError",
    "GlpiTaskState",
    "GlpiTicketContext",
    "GlpiTicketStatus",
    "GlpiTicketType",
    "GlpiTimelinePosition",
    "GlpiTimeoutError",
    "GlpiTransportError",
    "GlpiUserAuthType",
    "GlpiValidationError",
    "IdNameCompletenameRef",
    "IdNameRef",
    "IdRef",
    "PatchDocument",
    "PatchEntity",
    "PatchFollowup",
    "PatchKBArticle",
    "PatchKBArticleComment",
    "PatchKBCategory",
    "PatchLocation",
    "PatchSolution",
    "PatchTeamMember",
    "PatchTicket",
    "PatchTicketTask",
    "PatchTimelineDocument",
    "PatchUser",
    "PostDocument",
    "PostEntity",
    "PostFollowup",
    "PostKBArticle",
    "PostKBArticleComment",
    "PostKBCategory",
    "PostLocation",
    "PostPluginFieldsValueRow",
    "PostSolution",
    "PostTeamMember",
    "PostTicket",
    "PostTicketTask",
    "PostTimelineDocument",
    "PostUser",
    "TicketMarkdownOptions",
    "__version__",
    "changed_since",
    "created_between",
    "date_window",
]
