"""Public import surface for the GLPI Python client package.

The package re-exports two client classes:

* :class:`GlpiClient` — synchronous, blocking client (single source of
  truth for endpoint behaviour).
* :class:`AsyncGlpiClient` — asynchronous facade that wraps each
  synchronous method into a coroutine.

The ``api_schema`` and ``custom_schema`` Pydantic models are also
re-exported so downstream users can import them from a single stable
package root.
"""

from __future__ import annotations

from glpi_python_client.clients import AsyncGlpiClient, GlpiClient
from glpi_python_client.models import (
    DeleteDocument,
    DeleteEntity,
    DeleteFollowup,
    DeleteLocation,
    DeleteSolution,
    DeleteTeamMember,
    DeleteTicket,
    DeleteTicketTask,
    DeleteTimelineDocument,
    DeleteUser,
    GetDocument,
    GetEntity,
    GetFollowup,
    GetLocation,
    GetSolution,
    GetTeamMember,
    GetTicket,
    GetTicketTask,
    GetTimelineDocument,
    GetUser,
    GlpiEnum,
    GlpiGlobalValidation,
    GlpiPriority,
    GlpiSolutionStatus,
    GlpiTaskState,
    GlpiTicketContext,
    GlpiTicketStatus,
    GlpiTicketType,
    GlpiTimelinePosition,
    GlpiUserAuthType,
    IdNameCompletenameRef,
    IdNameRef,
    IdRef,
    PatchDocument,
    PatchEntity,
    PatchFollowup,
    PatchLocation,
    PatchSolution,
    PatchTeamMember,
    PatchTicket,
    PatchTicketTask,
    PatchTimelineDocument,
    PatchUser,
    PostDocument,
    PostEntity,
    PostFollowup,
    PostLocation,
    PostSolution,
    PostTeamMember,
    PostTicket,
    PostTicketTask,
    PostTimelineDocument,
    PostUser,
    TicketMarkdownOptions,
)

__version__ = "0.3.3"

__all__ = [
    "AsyncGlpiClient",
    "DeleteDocument",
    "DeleteEntity",
    "DeleteFollowup",
    "DeleteLocation",
    "DeleteSolution",
    "DeleteTeamMember",
    "DeleteTicket",
    "DeleteTicketTask",
    "DeleteTimelineDocument",
    "DeleteUser",
    "GetDocument",
    "GetEntity",
    "GetFollowup",
    "GetLocation",
    "GetSolution",
    "GetTeamMember",
    "GetTicket",
    "GetTicketTask",
    "GetTimelineDocument",
    "GetUser",
    "GlpiClient",
    "GlpiEnum",
    "GlpiGlobalValidation",
    "GlpiPriority",
    "GlpiSolutionStatus",
    "GlpiTaskState",
    "GlpiTicketContext",
    "GlpiTicketStatus",
    "GlpiTicketType",
    "GlpiTimelinePosition",
    "GlpiUserAuthType",
    "IdNameCompletenameRef",
    "IdNameRef",
    "IdRef",
    "PatchDocument",
    "PatchEntity",
    "PatchFollowup",
    "PatchLocation",
    "PatchSolution",
    "PatchTeamMember",
    "PatchTicket",
    "PatchTicketTask",
    "PatchTimelineDocument",
    "PatchUser",
    "PostDocument",
    "PostEntity",
    "PostFollowup",
    "PostLocation",
    "PostSolution",
    "PostTeamMember",
    "PostTicket",
    "PostTicketTask",
    "PostTimelineDocument",
    "PostUser",
    "TicketMarkdownOptions",
    "__version__",
]
