"""Public model exports for the GLPI client package.

The models are organised in two layers:

* :mod:`glpi_python_client.models.api_schema` -- raw Pydantic shapes that
  mirror ``docs/glpi_api_contract.json`` one for one, apart from the
  rich-text slots documented there. One model per HTTP verb is exposed
  under the ``Get<Name>``, ``Post<Name>``, ``Patch<Name>`` and
  ``Delete<Name>`` naming convention. Use these models from new client
  mixins.
* :mod:`glpi_python_client.models.custom_schema` -- aggregated views, such
  as :class:`GlpiTicketContext`, that group several API objects into one
  richer payload.
"""

from __future__ import annotations

from glpi_python_client.models.api_schema._common import (
    IdNameCompletenameRef,
    IdNameRef,
    IdRef,
)
from glpi_python_client.models.api_schema.administration import (
    DeleteEntity,
    DeleteUser,
    GetEntity,
    GetUser,
    PatchEntity,
    PatchUser,
    PostEntity,
    PostUser,
)
from glpi_python_client.models.api_schema.assets import (
    DeleteComputer,
    GetComputer,
    PatchComputer,
    PostComputer,
)
from glpi_python_client.models.api_schema.assistance import (
    DeleteTeamMember,
    DeleteTicket,
    GetTeamMember,
    GetTicket,
    PatchTeamMember,
    PatchTicket,
    PostTeamMember,
    PostTicket,
)
from glpi_python_client.models.api_schema.assistance.timeline import (
    DeleteFollowup,
    DeleteSolution,
    DeleteTicketTask,
    DeleteTimelineDocument,
    GetFollowup,
    GetSolution,
    GetTicketTask,
    GetTimelineDocument,
    PatchFollowup,
    PatchSolution,
    PatchTicketTask,
    PatchTimelineDocument,
    PostFollowup,
    PostSolution,
    PostTicketTask,
    PostTimelineDocument,
)
from glpi_python_client.models.api_schema.dropdowns import (
    DeleteContractType,
    DeleteLocation,
    GetContractType,
    GetLocation,
    PatchContractType,
    PatchLocation,
    PostContractType,
    PostLocation,
)
from glpi_python_client.models.api_schema.enums import (
    GlpiContractRenewalType,
    GlpiEnum,
    GlpiGlobalValidation,
    GlpiPriority,
    GlpiSolutionStatus,
    GlpiTaskState,
    GlpiTicketStatus,
    GlpiTicketType,
    GlpiTimelinePosition,
    GlpiUserAuthType,
)
from glpi_python_client.models.api_schema.knowledgebase import (
    DeleteKBArticle,
    DeleteKBArticleComment,
    DeleteKBCategory,
    GetKBArticle,
    GetKBArticleComment,
    GetKBArticleRevision,
    GetKBCategory,
    PatchKBArticle,
    PatchKBArticleComment,
    PatchKBCategory,
    PostKBArticle,
    PostKBArticleComment,
    PostKBCategory,
)
from glpi_python_client.models.api_schema.management import (
    DeleteContract,
    DeleteContractCost,
    DeleteDocument,
    GetContract,
    GetContractCost,
    GetDocument,
    PatchContract,
    PatchContractCost,
    PatchDocument,
    PostContract,
    PostContractCost,
    PostDocument,
)
from glpi_python_client.models.api_schema.plugins import (
    GetPluginFieldsContainer,
    GetPluginFieldsField,
    GetPluginFieldsValueRow,
    PostPluginFieldsValueRow,
)
from glpi_python_client.models.custom_schema import (
    GlpiTicketContext,
    TicketMarkdownOptions,
)

__all__ = [
    "DeleteComputer",
    "DeleteContract",
    "DeleteContractCost",
    "DeleteContractType",
    "DeleteDocument",
    "DeleteEntity",
    "DeleteFollowup",
    "DeleteKBArticle",
    "DeleteKBArticleComment",
    "DeleteKBCategory",
    "DeleteLocation",
    "DeleteSolution",
    "DeleteTeamMember",
    "DeleteTicket",
    "DeleteTicketTask",
    "DeleteTimelineDocument",
    "DeleteUser",
    "GetComputer",
    "GetContract",
    "GetContractCost",
    "GetContractType",
    "GetDocument",
    "GetEntity",
    "GetFollowup",
    "GetKBArticle",
    "GetKBArticleComment",
    "GetKBArticleRevision",
    "GetKBCategory",
    "GetLocation",
    "GetPluginFieldsContainer",
    "GetPluginFieldsField",
    "GetPluginFieldsValueRow",
    "GetSolution",
    "GetTeamMember",
    "GetTicket",
    "GetTicketTask",
    "GetTimelineDocument",
    "GetUser",
    "GlpiContractRenewalType",
    "GlpiEnum",
    "GlpiGlobalValidation",
    "GlpiPriority",
    "GlpiSolutionStatus",
    "GlpiTaskState",
    "GlpiTicketContext",
    "GlpiTicketStatus",
    "GlpiTicketType",
    "GlpiTimelinePosition",
    "GlpiUserAuthType",
    "IdNameCompletenameRef",
    "IdNameRef",
    "IdRef",
    "PatchComputer",
    "PatchContract",
    "PatchContractCost",
    "PatchContractType",
    "PatchDocument",
    "PatchEntity",
    "PatchFollowup",
    "PatchKBArticle",
    "PatchKBArticleComment",
    "PatchKBCategory",
    "PatchLocation",
    "PatchSolution",
    "PatchTeamMember",
    "PatchTicket",
    "PatchTicketTask",
    "PatchTimelineDocument",
    "PatchUser",
    "PostComputer",
    "PostContract",
    "PostContractCost",
    "PostContractType",
    "PostDocument",
    "PostEntity",
    "PostFollowup",
    "PostKBArticle",
    "PostKBArticleComment",
    "PostKBCategory",
    "PostLocation",
    "PostPluginFieldsValueRow",
    "PostSolution",
    "PostTeamMember",
    "PostTicket",
    "PostTicketTask",
    "PostTimelineDocument",
    "PostUser",
    "TicketMarkdownOptions",
]
